/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package mscorlib_dll.system;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Exception implements mscorlib_dll.system.runtime.serialization.ISerializable, mscorlib_dll.system.runtime.interopservices._Exception {
    public com.sun.jna.Pointer __object;

    public Exception(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public Exception() {
        __object = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Exception(String message) {
        __object = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_new_1(message);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String getMessage() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_get_Message(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public String getStackTrace() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_get_StackTrace(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public String getHelpLink() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_get_HelpLink(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setHelpLink(String value) {
        mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_set_HelpLink(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String getSource() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_get_Source(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setSource(String value) {
        mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_set_Source(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String toString() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public int getHResult() {
        int __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Exception_get_HResult(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
