/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.exceptions;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Base {
    public com.sun.jna.Pointer __object;

    public Base(com.sun.jna.Pointer object) { this.__object = object; }

    public Base(boolean broken) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Exceptions_Base_new((byte)(broken? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }
}
