/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.exceptions;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Super extends managed_dll.exceptions.Base {
    public Super(com.sun.jna.Pointer object) { super(object); }

    public Super(boolean broken) {
        super((com.sun.jna.Pointer)null);
        __object = managed_dll.Native_managed_dll.INSTANCE.Exceptions_Super_new((byte)(broken? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }
}
