/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package mscorlib_dll.system.runtime.interopservices;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class _ExceptionImpl implements mscorlib_dll.system.runtime.interopservices._Exception {
    public com.sun.jna.Pointer __object;

    public _ExceptionImpl(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    @Override
    public String getHelpLink() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_get_HelpLink(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    @Override
    public void setHelpLink(String value) {
        mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_set_HelpLink(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    @Override
    public String getMessage() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_get_Message(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    @Override
    public String getSource() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_get_Source(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    @Override
    public void setSource(String value) {
        mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_set_Source(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    @Override
    public String getStackTrace() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_get_StackTrace(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    @Override
    public String toString() {
        String __ret = mscorlib_dll.Native_mscorlib_dll.INSTANCE.System_Runtime_InteropServices__Exception_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
