/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package mscorlib_dll.system.runtime.interopservices;

import mono.embeddinator.*;
import com.sun.jna.*;

public interface _Exception {
    public String getHelpLink();

    public void setHelpLink(String value);

    public String getMessage();

    public String getSource();

    public void setSource(String value);

    public String getStackTrace();

    public String toString();

    public com.sun.jna.Pointer __getObject();
}
