/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.equalshashoverrides;

import mono.embeddinator.*;
import com.sun.jna.*;

public class EquatableClass {
    public com.sun.jna.Pointer __object;

    public EquatableClass(com.sun.jna.Pointer object) { this.__object = object; }

    public EquatableClass(int y) {
        __object = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableClass_new(y);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getY() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableClass_get_Y(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setY(int value) {
        managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableClass_set_Y(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public final boolean equals(managed_dll.equalshashoverrides.Class obj) {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableClass_Equals(__object, obj == null ? null : obj.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
