/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.equalshashoverrides;

import mono.embeddinator.*;
import com.sun.jna.*;

public class EquatableInt {
    public com.sun.jna.Pointer __object;

    public EquatableInt(com.sun.jna.Pointer object) { this.__object = object; }

    public EquatableInt(int y) {
        __object = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableInt_new(y);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getY() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableInt_get_Y(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setY(int value) {
        managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableInt_set_Y(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public final boolean equals(int obj) {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.EqualsHashOverrides_EquatableInt_Equals(__object, obj);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
