/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.interfaces;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class IMakeItUpImpl implements managed_dll.interfaces.IMakeItUp {
    public com.sun.jna.Pointer __object;

    public IMakeItUpImpl(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    @Override
    public boolean getBoolean() {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_IMakeItUp_get_Boolean(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    @Override
    public String convert(int integer) {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_IMakeItUp_Convert(__object, integer);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    @Override
    public String convert_1(long longint) {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_IMakeItUp_Convert(__object, longint);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
