/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.interfaces;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class IOperationsImpl implements managed_dll.interfaces.IOperations {
    public com.sun.jna.Pointer __object;

    public IOperationsImpl(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    @Override
    public int addInt(int a, int b) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_IOperations_AddInt(__object, a, b);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
