/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.interfaces;

import mono.embeddinator.*;
import com.sun.jna.*;

public interface IOperations {
    public int addInt(int a, int b);

    public com.sun.jna.Pointer __getObject();
}
