/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.interfaces;

import mono.embeddinator.*;
import com.sun.jna.*;

public class OpConsumer {
    public com.sun.jna.Pointer __object;

    public OpConsumer(com.sun.jna.Pointer object) { this.__object = object; }

    public OpConsumer() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Interfaces_OpConsumer_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public static int doAddition(managed_dll.interfaces.IOperations ops, int a, int b) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_OpConsumer_DoAddition(ops == null ? null : ops.__getObject(), a, b);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static boolean testManagedAdder(int a, int b) {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_OpConsumer_TestManagedAdder(a, b);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
