/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.interfaces;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Supplier {
    public com.sun.jna.Pointer __object;

    public Supplier(com.sun.jna.Pointer object) { this.__object = object; }

    public static managed_dll.interfaces.IMakeItUp create() {
        com.sun.jna.Pointer __ret = managed_dll.Native_managed_dll.INSTANCE.Interfaces_Supplier_Create();
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new managed_dll.interfaces.IMakeItUpImpl(__ret));
    }
}
