/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.arrays;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Arr {
    public com.sun.jna.Pointer __object;

    public Arr(com.sun.jna.Pointer object) { this.__object = object; }

    public Arr() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Arrays_Arr_new();
        mono.embeddinator.Runtime.checkExceptions();
    }
}
