/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.first.second.third;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ClassWithNestedNamespace {
    public com.sun.jna.Pointer __object;

    public ClassWithNestedNamespace(com.sun.jna.Pointer object) { this.__object = object; }

    public ClassWithNestedNamespace() {
        __object = managed_dll.Native_managed_dll.INSTANCE.First_Second_Third_ClassWithNestedNamespace_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String toString() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.First_Second_Third_ClassWithNestedNamespace_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
