/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ClassWithoutNamespace {
    public com.sun.jna.Pointer __object;

    public ClassWithoutNamespace(com.sun.jna.Pointer object) { this.__object = object; }

    public ClassWithoutNamespace() {
        __object = managed_dll.Native_managed_dll.INSTANCE.ClassWithoutNamespace_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String toString() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.ClassWithoutNamespace_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
