/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Type_String {
    public com.sun.jna.Pointer __object;

    public Type_String(com.sun.jna.Pointer object) { this.__object = object; }

    public static String getNullString() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Type_String_get_NullString();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static String getEmptyString() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Type_String_get_EmptyString();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static String getNonEmptyString() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Type_String_get_NonEmptyString();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
