/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Type_Decimal {
    public com.sun.jna.Pointer __object;

    public Type_Decimal(com.sun.jna.Pointer object) { this.__object = object; }

}
