/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class BoolCollection {
    public com.sun.jna.Pointer __object;

    public BoolCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public BoolCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(boolean item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_Add(__object, (byte)(item? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(boolean item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_Remove(__object, (byte)(item? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public boolean getItem(int index) {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setItem(int index, boolean value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_BoolCollection_set_Item(__object, index, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }
}
