/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ByteCollection {
    public com.sun.jna.Pointer __object;

    public ByteCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public ByteCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(UnsignedByte item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(UnsignedByte item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public UnsignedByte getItem(int index) {
        UnsignedByte __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, UnsignedByte value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ByteCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
