/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class CharCollection {
    public com.sun.jna.Pointer __object;

    public CharCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public CharCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(char item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(char item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public char getItem(int index) {
        char __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, char value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_CharCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
