/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class FloatCollection {
    public com.sun.jna.Pointer __object;

    public FloatCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public FloatCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(float item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(float item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public float getItem(int index) {
        float __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, float value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_FloatCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
