/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class IntCollection {
    public com.sun.jna.Pointer __object;

    public IntCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public IntCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(int item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(int item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public int getItem(int index) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, int value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
