/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class IntCollectionNoSetter {
    public com.sun.jna.Pointer __object;

    public IntCollectionNoSetter(com.sun.jna.Pointer object) { this.__object = object; }

    public IntCollectionNoSetter() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollectionNoSetter_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getItem(int index) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_IntCollectionNoSetter_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
