/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class LongCollection {
    public com.sun.jna.Pointer __object;

    public LongCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public LongCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(long item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(long item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public long getItem(int index) {
        long __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, long value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_LongCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
