/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class SbyteCollection {
    public com.sun.jna.Pointer __object;

    public SbyteCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public SbyteCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(byte item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(byte item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public byte getItem(int index) {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, byte value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_SbyteCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
