/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ShortCollection {
    public com.sun.jna.Pointer __object;

    public ShortCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public ShortCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(short item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(short item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public short getItem(int index) {
        short __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, short value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_ShortCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
