/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class UintCollection {
    public com.sun.jna.Pointer __object;

    public UintCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public UintCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(UnsignedInt item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(UnsignedInt item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public UnsignedInt getItem(int index) {
        UnsignedInt __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, UnsignedInt value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UintCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
