/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class UlongCollection {
    public com.sun.jna.Pointer __object;

    public UlongCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public UlongCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(UnsignedLong item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(UnsignedLong item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public UnsignedLong getItem(int index) {
        UnsignedLong __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, UnsignedLong value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UlongCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
