/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.subscripts;

import mono.embeddinator.*;
import com.sun.jna.*;

public class UshortCollection {
    public com.sun.jna.Pointer __object;

    public UshortCollection(com.sun.jna.Pointer object) { this.__object = object; }

    public UshortCollection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(UnsignedShort item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_Add(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(UnsignedShort item) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_Remove(__object, item);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public UnsignedShort getItem(int index) {
        UnsignedShort __ret = managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setItem(int index, UnsignedShort value) {
        managed_dll.Native_managed_dll.INSTANCE.Subscripts_UshortCollection_set_Item(__object, index, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
