/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.comparable;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Different {
    public com.sun.jna.Pointer __object;

    public Different(com.sun.jna.Pointer object) { this.__object = object; }

    public Different(int i) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Comparable_Different_new(i);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getInteger() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Comparable_Different_get_Integer(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public final int compareTo(managed_dll.comparable.Generic generic) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Comparable_Different_CompareTo(__object, generic == null ? null : generic.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public final int compareTo_1(int integer) {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Comparable_Different_CompareTo(__object, integer);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
