/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.properties;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Query {
    public com.sun.jna.Pointer __object;

    public Query(com.sun.jna.Pointer object) { this.__object = object; }

    public Query() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public static int getUniversalAnswer() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_get_UniversalAnswer();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public boolean getIsGood() {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_get_IsGood(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public boolean getIsBad() {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_get_IsBad(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public int getAnswer() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_get_Answer(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setAnswer(int value) {
        managed_dll.Native_managed_dll.INSTANCE.Properties_Query_set_Answer(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void setSecret(int value) {
        managed_dll.Native_managed_dll.INSTANCE.Properties_Query_set_Secret(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getIsSecret() {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Properties_Query_get_IsSecret(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
