/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.methods;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Collection {
    public com.sun.jna.Pointer __object;

    public Collection(com.sun.jna.Pointer object) { this.__object = object; }

    public Collection() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void add(managed_dll.methods.Item item) {
        managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_Add(__object, item == null ? null : item.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void remove(managed_dll.methods.Item item) {
        managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_Remove(__object, item == null ? null : item.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getCount() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_get_Count(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public managed_dll.methods.Item getItem(int index) {
        com.sun.jna.Pointer __ret = managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_get_Item(__object, index);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new managed_dll.methods.Item(__ret));
    }

    public void setItem(int index, managed_dll.methods.Item value) {
        managed_dll.Native_managed_dll.INSTANCE.Methods_Collection_set_Item(__object, index, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
