/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.constructors;

import mono.embeddinator.*;
import com.sun.jna.*;

public class AllTypeCode {
    public com.sun.jna.Pointer __object;

    public AllTypeCode(com.sun.jna.Pointer object) { this.__object = object; }

    public AllTypeCode(boolean b1, char c2, String s) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_AllTypeCode_new((byte)(b1? 1 : 0), c2, s);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public AllTypeCode(byte i8, short i16, int i32, long i64) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_AllTypeCode_new_1(i8, i16, i32, i64);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public AllTypeCode(UnsignedByte u8, UnsignedShort u16, UnsignedInt u32, UnsignedLong u64) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_AllTypeCode_new_2(u8, u16, u32, u64);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public AllTypeCode(float f32, double f64) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_AllTypeCode_new_3(f32, f64);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getTestResult() {
        byte __ret = managed_dll.Native_managed_dll.INSTANCE.Constructors_AllTypeCode_get_TestResult(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
