/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.constructors;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Duplicates {
    public com.sun.jna.Pointer __object;

    public Duplicates(com.sun.jna.Pointer object) { this.__object = object; }

    public Duplicates(UnsignedByte b, short s, int i, long l) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Duplicates_new(b, s, i, l);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Duplicates(int b, int s, int i, int l) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Duplicates_new_1(b, s, i, l);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Duplicates(UnsignedByte b, UnsignedByte s, UnsignedByte i, UnsignedByte l) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Duplicates_new_2(b, s, i, l);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
