/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.constructors;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Implicit {
    public com.sun.jna.Pointer __object;

    public Implicit(com.sun.jna.Pointer object) { this.__object = object; }

    public Implicit() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Implicit_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public String getTestResult() {
        String __ret = managed_dll.Native_managed_dll.INSTANCE.Constructors_Implicit_get_TestResult(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
