/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.constructors;

import mono.embeddinator.*;
import com.sun.jna.*;

public class SuperUnique extends managed_dll.constructors.Unique {
    public SuperUnique(com.sun.jna.Pointer object) { super(object); }

    public SuperUnique() {
        super((com.sun.jna.Pointer)null);
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_SuperUnique_new();
        mono.embeddinator.Runtime.checkExceptions();
    }
}
