/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.constructors;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Unique {
    public com.sun.jna.Pointer __object;

    public Unique(com.sun.jna.Pointer object) { this.__object = object; }

    public Unique() {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Unique_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Unique(int id) {
        __object = managed_dll.Native_managed_dll.INSTANCE.Constructors_Unique_new_1(id);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getId() {
        int __ret = managed_dll.Native_managed_dll.INSTANCE.Constructors_Unique_get_Id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
