/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.enums;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class ByteFlags {
    public static final ByteFlags Empty = new ByteFlags((int)0);
    public static final ByteFlags Bit0 = new ByteFlags((int)1);
    public static final ByteFlags Bit1 = new ByteFlags((int)2);
    public static final ByteFlags Bit2 = new ByteFlags((int)4);
    public static final ByteFlags Bit3 = new ByteFlags((int)8);
    public static final ByteFlags Bit4 = new ByteFlags((int)16);
    public static final ByteFlags Bit5 = new ByteFlags((int)32);
    public static final ByteFlags Bit6 = new ByteFlags((int)64);
    public static final ByteFlags Bit7 = new ByteFlags((int)128);

    private final int id;
    ByteFlags(int id) { this.id = id; }
    public int getValue() { return id; }

    public static ByteFlags fromOrdinal(int n) {
        return valuesMap.containsKey(n) ? valuesMap.get(n) : new ByteFlags(n);
    }

    private static final java.util.Map<Integer, ByteFlags> valuesMap = 
        new java.util.HashMap<Integer, ByteFlags>();

    static {
        try {
            java.lang.reflect.Field[] constants = ByteFlags.class.getFields();
            for (final java.lang.reflect.Field field : constants) {
                ByteFlags item = (ByteFlags) field.get(null);
                valuesMap.put(item.getValue(), item);
            }
        } catch(java.lang.IllegalAccessException ex) {
        }
    }
}
