/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package managed_dll.enums;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class ShortEnum {
    public static final ShortEnum Min = new ShortEnum((short)-32768);
    public static final ShortEnum Max = new ShortEnum((short)32767);

    private final short id;
    ShortEnum(short id) { this.id = id; }
    public short getValue() { return id; }

    public static ShortEnum fromOrdinal(short n) {
        return valuesMap.containsKey(n) ? valuesMap.get(n) : new ShortEnum(n);
    }

    private static final java.util.Map<Short, ShortEnum> valuesMap = 
        new java.util.HashMap<Short, ShortEnum>();

    static {
        try {
            java.lang.reflect.Field[] constants = ShortEnum.class.getFields();
            for (final java.lang.reflect.Field field : constants) {
                ShortEnum item = (ShortEnum) field.get(null);
                valuesMap.put(item.getValue(), item);
            }
        } catch(java.lang.IllegalAccessException ex) {
        }
    }
}
